#!/usr/bin/env bash
# copy file to server

usage="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $# -ne 4 ]
then
    echo "$usage"
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
