#!/usr/bin/env bash
# copy file to server

usage="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $# -ne 4 ]
then
    echo "$usage"
fi
echo -e "Host *\n\tStrictHostKeyChecking no" >> "$HOME/.ssh/config"
scp -i "$4" "$HOME/$1" "$3@$2"
